Repository timtimjnvr/ideat, pull requests merged in 2021-12, with the labels that each got.

#6 feat: REST Server written in DART
  server/ideat_server/.gitignore
  server/ideat_server/.travis.yml
  server/ideat_server/README.md
  server/ideat_server/analysis_options.yaml
  server/ideat_server/bin/main.dart
  server/ideat_server/config.src.yaml
  server/ideat_server/config.yaml
  server/ideat_server/lib/ApiController.dart
  server/ideat_server/lib/channel.dart
  server/ideat_server/lib/ideat_server.dart
  server/ideat_server/pubspec.lock
  server/ideat_server/pubspec.yaml
  server/ideat_server/test/example_test.dart
  server/ideat_server/test/harness/app.dart
Labels: enhancement

#9 Webscraper returning JSON array of products found on Amazon
  .gitignore
  webscraper/.gitignore
  webscraper/CHANGELOG.md
  webscraper/README.md
  webscraper/analysis_options.yaml
  webscraper/bin/webscraper.dart
  webscraper/lib/product.dart
  webscraper/lib/webscraper.dart
  webscraper/pubspec.lock
  webscraper/pubspec.yaml
  webscraper/test/webscraper_test.dart
Labels: web scraper

#16 test: ci on webscraper
  webscraper/test/webscraper_test.dart
Labels: web scraper

#17 ci: add automatic changelogs
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: enhancement, cicd

#19 fix: fix versioning in yaml
  ideat/pubspec.yaml
Labels: bug, cicd

#20 feat: recipes webscraper using npm module marmiton-api fix #18
  webscraper-recipies/.gitignore
  webscraper-recipies/index.ts
  webscraper-recipies/package-lock.json
  webscraper-recipies/package.json
Labels: enhancement
